#!/usr/bin/env bash
# Displays username, user id, and home directory path for each user in /etc/passwd


# Open the /etc/passwd file for reading
while read -r 
do
	cut -f1,4,6 -d':'
done < /etc/passwd
