#!/usr/bin/env bash
# Displays username, user id, and home directory path for each user in /etc/passwd

# Set the field separator to ":"
IFS=":"

# Open the /etc/passwd file for reading
while read -r username _ uid _ home_dir _
do
    echo "$username:$uid:$home_dir"
done < /etc/passwd
