#!/usr/bin/env bash
# Displays "Best School" 10 times, and on the 9th iteration, adds "Hi" on a new line

count=0
while [ "$count" -lt 10 ]
do
    if [ "$count" -eq 8 ]
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    ((count++))
done
