#!/usr/bin/env bash
# Displays time in HH:MM format using a while loop

hour=0
while [ "$hour" -le 12 ]
do
    minute=1
    while [ "$minute" -le 59 ]
    do
        printf "%02d:%02d\n" "$hour" "$minute"
        ((minute++))
    done
    ((hour++))
done
