#!/usr/bin/env bash
# Displays content of the current directory in list format, showing only part of the name after the first dash

filename=school

if test -e $filename;
then
	echo "$filename file exists"
#	if test -f $filename
#	then
		if [ -s "$filename" ]
		then
			echo "$filename file is not empty"
		else
			echo "$filename file is empty"
#		fi
	fi
	if test -f $filename
	then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
